Add option to pass block to controller's #save!
RIPAGlobal/scimitar pull request #73
Opened 2023-10-18 13:34 UTC by s-andringa

Hi @pond, it's me [again](https://github.com/RIPAGlobal/scimitar/pull/71).

This time I extended `ActiveRecordBackedResourcesController#save!` to accept a block, so that subclasses may override the default `record.save!` call with their own saving logic, without having to reimplement the rescue clause for handling uniqueness errors. Also, it aligns nicely with the destroy action, which already accepts a block for a very similar reasons.

In our case we would like a service object to save the record and do some other stuff, because we do not want to employ AR callbacks for that other stuff. With these changes it can look like this:

```rb
def save!(_record)
  super do |record|
    Services::ManagedUser::Save.new(record).call
  end
end
```

I would love to see this merged in one form or another. Thanks!

2023-10-23 20:45 UTC, pond requested changes
Looks great & only requesting changes on RDoc on the new method as I have to be a stickler for details like that in a public gem where docs are particularly important.

No other changes tho, on the money overall! Thanks.

2023-10-23 20:45 UTC, pond commented on app/controllers/scimitar/active_record_backed_resources_controller.rb
> +      def handle_invalid_record(record)
This refactor is nice, but I'm of course going to ask for docs :joy: - just a brief RDoc comment, same pattern as `save!`  itself.

2023-10-30 15:39 UTC, s-andringa commented
Thanks @pond. I just pushed the RDoc comment for #handle_invalid_record.

Did you have a chance to look at my other PR https://github.com/RIPAGlobal/scimitar/pull/71 ?

2023-10-30 22:05 UTC, pond commented
@s-andringa Yes, sorry it took a while. Only major request you'll see over there is a `README.md` addition.

Merging here, it's good to go. Thanks! I'll compile a few of the current PRs together and hope to do a new gem version release pretty soon.

2023-10-30 22:06 UTC, pond approved these changes

2023-10-30 22:06 UTC, merged

2023-11-01 08:55 UTC, s-andringa commented
> I'll compile a few of the current PRs together and hope to do a new gem version release pretty soon.

That'd be great. Thank you.

2023-11-15 01:18 UTC, pond commented
This is now available via RubyGems in v2.6.0 / v1.7.0.

2023-11-16 13:12 UTC, s-andringa commented
Great, thanks @pond!